In [1]:
import torch
import numpy as np

In [2]:
#pytorch datatypes - tensors

In [2]:
torch.tensor(10)

tensor(10)

In [3]:
torch.tensor([1, 2, 3])


tensor([1, 2, 3])

In [4]:
scalar = torch.tensor(10)

In [5]:
type(scalar)

torch.Tensor

In [6]:
scalar

tensor(10)

In [7]:
scalar+5

tensor(15)

In [8]:
scalar /2


tensor(5.)

In [9]:
scalar *3

tensor(30)

In [10]:
scalar.dim()

0

In [12]:
#Vector
#count #of [ -> dimensions
#count #of elements -> shape


In [13]:
matrix=torch.tensor([[1,2],[3,4]])

In [14]:
matrix

tensor([[1, 2],
        [3, 4]])

In [15]:
matrix.dim()

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
tensor_example=torch.tensor([[[1,2,3],
                              [4,5,6],  
                              [7,8,9]]])

In [18]:
tensor_example

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
tensor_example.dim()


3

In [20]:
tensor_example.shape

torch.Size([1, 3, 3])

In [22]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None, #cpu or gpu
                            requires_grad=False
                            
                            )

In [23]:
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype


torch.float32